In [ ]:
ans 1

In [2]:
#Yes, there is a difference in the data types of variables list_ and array_list. The variable list_ is a Python list, while array_list is a NumPy array. You can use the type() function to print the data types of both variables. Here's the code:

import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object=list_)

# Print data types
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [ ]:
ans 2

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in list_
print("Data types of elements in list_:")
for item in list_:
    print(type(item))

# Print data type of each element in array_list
print("Data types of elements in array_list:")
for item in array_list:
    print(type(item))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
ans 3

In [ ]:
Yes, there will be a difference in the data type of the elements present
in the variables list_ and array_list when you modify array_list using 
dtype=int. In this case, the elements in array_list will be of data 
type int instead of strings. Here's the code to print the data types of 
each element in both variables:

In [5]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
print("Data types of elements in list_:")
for item in list_:
    print(type(item))

# Print data type of each element in array_list
print("Data types of elements in array_list:")
for item in array_list:
    print(type(item))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
ans 4

In [6]:
#You can find the shape and size of a NumPy array using the shape and size attributes, respectively. Here's the code to find these characteristics of the variable num_array:

import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Shape
shape = num_array.shape

# (ii) Size
size = num_array.size

print("Shape of num_array:", shape)
print("Size of num_array:", size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [ ]:
ans 5

In [8]:
import numpy as np

# Create a 3x3 array containing zeros
zeros_array = np.zeros((3, 3))

print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ans 6

In [9]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
